package com.tajos.studio.activities;

import com.tajos.studio.GradeApp;
import com.tajos.studio.js.adapter.JavascriptInterfaceAdapter;
import com.tajos.studio.net.DBManager;
import com.tajos.studio.util.GradeUtils;
import java.awt.Cursor;
import javax.swing.ImageIcon;

/**
 *
 * @author Rene Tajos Jr.
 */
public class SplashActivity extends javax.swing.JFrame {

    private boolean isWaitingCursor = false;
    
    /**
     * Creates new form SplashActivity
     */
    public SplashActivity() {
        initComponents();
        init();
    }
    
    private void init() {
        GradeUtils.centerFrame(this);
        
        DBManager.getInstance().getJavaScriptInterface()
                .addJavascriptInterfaceListener(new JavascriptInterfaceAdapter() {
            @Override
            public void isSignedOut() {
                setCursor(Cursor.getDefaultCursor());
                isWaitingCursor = false;
                setVisible(false);
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel1 = new com.tajos.studio.components.BackgroundPanel();
        globePanel = new javax.swing.JPanel();
        globeImg = new com.tajos.studio.components.ImageViewer();
        toolbar = new javax.swing.JPanel();
        minimizedButton1 = new com.tajos.studio.components.MinimizedButton();
        closeButton1 = new com.tajos.studio.components.CloseButton();
        welcomeLbl = new com.tajos.studio.components.TajosJLabel();
        appLogoImg = new com.tajos.studio.components.ImageViewer();
        appNameLbl = new com.tajos.studio.components.TajosJLabel();
        dscrptionLbl = new com.tajos.studio.components.TTextArea();
        proceedPanel = new javax.swing.JPanel();
        proceedLbl = new com.tajos.studio.components.TajosJLabel();
        proceedArrow = new com.tajos.studio.components.ImageViewer();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        backgroundPanel1.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 28, 72)));

        globePanel.setOpaque(false);
        globePanel.setLayout(null);

        globeImg.setImageResource(new javax.swing.ImageIcon(getClass().getResource("/res/globe.png"))); // NOI18N
        globePanel.add(globeImg);
        globeImg.setBounds(50, 20, 230, 280);

        toolbar.setBackground(new java.awt.Color(247, 245, 251));
        toolbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                toolbarMouseDragged(evt);
            }
        });
        toolbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                toolbarMousePressed(evt);
            }
        });
        toolbar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        minimizedButton1.attachFrame(this);
        toolbar.add(minimizedButton1);

        closeButton1.setText("closeButton1");
        toolbar.add(closeButton1);

        welcomeLbl.setForeground(new java.awt.Color(22, 28, 72));
        welcomeLbl.setText("Welcome!");
        welcomeLbl.setDefaultFont(30);

        appLogoImg.setImageResource(new javax.swing.ImageIcon(getClass().getResource("/res/grading-logo.png"))); // NOI18N

        appNameLbl.setForeground(new java.awt.Color(22, 28, 72));
        appNameLbl.setText("graede");
        appNameLbl.setBoldDefaultFont(40);

        dscrptionLbl.setEditable(false);
        dscrptionLbl.setBackground(new java.awt.Color(255, 255, 255));
        dscrptionLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dscrptionLbl.setColumns(20);
        dscrptionLbl.setForeground(new java.awt.Color(22, 28, 72));
        dscrptionLbl.setRows(5);
        dscrptionLbl.setText("Graede brings all of your class grades in one place, \nmaking them instantly searchable and accessible \nfrom anywhere.\n\nOur goal is to provide you a service that\nwill make sending grades to students hassle-free, \nto make your school life easier, and more productive.\n\nWe also provide a grade viewer for students where they \ncan view their grades anytime and anywhere using their smart\nphones.");
        dscrptionLbl.setDefaultFont(11);
        dscrptionLbl.setFocusable(false);

        proceedPanel.setOpaque(false);
        proceedPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                proceedPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                proceedPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                proceedPanelMousePressed(evt);
            }
        });
        com.tajos.studio.layoutmanagers.GravityLayout gravityLayout1 = new com.tajos.studio.layoutmanagers.GravityLayout();
        gravityLayout1.setGravity(com.tajos.studio.layoutmanagers.GravityLayout.Gravity.CENTER);
        gravityLayout1.setOrientation(com.tajos.studio.layoutmanagers.GravityLayout.Orientation.HORIZONTAL);
        gravityLayout1.setHorizontalGap(5);
        proceedPanel.setLayout(gravityLayout1);

        proceedLbl.setForeground(new java.awt.Color(22, 28, 72));
        proceedLbl.setText("Let's Proceed");
        proceedLbl.setDefaultFont(16);
        proceedPanel.add(proceedLbl);

        proceedArrow.setColorImage(new java.awt.Color(22, 28, 72));
        proceedArrow.setImageResource(new javax.swing.ImageIcon(getClass().getResource("/icons/right-arrow.png"))); // NOI18N
        proceedArrow.setPreferredSize(new java.awt.Dimension(50, 30));
        proceedPanel.add(proceedArrow);

        javax.swing.GroupLayout backgroundPanel1Layout = new javax.swing.GroupLayout(backgroundPanel1);
        backgroundPanel1.setLayout(backgroundPanel1Layout);
        backgroundPanel1Layout.setHorizontalGroup(
            backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundPanel1Layout.createSequentialGroup()
                .addGroup(backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(appLogoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(appNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(dscrptionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(proceedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 99, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(globePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        backgroundPanel1Layout.setVerticalGroup(
            backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanel1Layout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(appNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(appLogoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(backgroundPanel1Layout.createSequentialGroup()
                        .addComponent(dscrptionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(backgroundPanel1Layout.createSequentialGroup()
                        .addComponent(proceedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(globePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private int mouseInputX, mouseInputY;
    private void toolbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolbarMousePressed
        mouseInputX = evt.getX();
        mouseInputY = evt.getY();
    }//GEN-LAST:event_toolbarMousePressed

    private void toolbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolbarMouseDragged
        int x = evt.getXOnScreen() - mouseInputX;
        int y = evt.getYOnScreen() - mouseInputY;
        setLocation(x, y);
    }//GEN-LAST:event_toolbarMouseDragged

    private void proceedPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceedPanelMousePressed
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        isWaitingCursor = true;
        GradeApp.instance().init();
    }//GEN-LAST:event_proceedPanelMousePressed

    private void proceedPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceedPanelMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_proceedPanelMouseEntered

    private void proceedPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceedPanelMouseExited
        setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_proceedPanelMouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ImageIcon icon = new ImageIcon(WorkBookActivity.class.getResource("/res/grading-logo.png"));
        setIconImage(icon.getImage());
        setTitle("Graede");
    }//GEN-LAST:event_formWindowActivated

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        if (isWaitingCursor)
            setCursor(new Cursor(Cursor.WAIT_CURSOR));
    }//GEN-LAST:event_formMouseMoved

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.tajos.studio.components.ImageViewer appLogoImg;
    private com.tajos.studio.components.TajosJLabel appNameLbl;
    private com.tajos.studio.components.BackgroundPanel backgroundPanel1;
    private com.tajos.studio.components.CloseButton closeButton1;
    private com.tajos.studio.components.TTextArea dscrptionLbl;
    private com.tajos.studio.components.ImageViewer globeImg;
    private javax.swing.JPanel globePanel;
    private com.tajos.studio.components.MinimizedButton minimizedButton1;
    private com.tajos.studio.components.ImageViewer proceedArrow;
    private com.tajos.studio.components.TajosJLabel proceedLbl;
    private javax.swing.JPanel proceedPanel;
    private javax.swing.JPanel toolbar;
    private com.tajos.studio.components.TajosJLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
