package com.tajos.studio.dialogs;

import com.tajos.studio.GradeApp;
import com.tajos.studio.activities.WorkBookActivity;
import com.tajos.studio.data.FilteredData;
import com.tajos.studio.util.GradeUtils;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author Rene Tajos Jr
 */
public class FilterDialog extends javax.swing.JDialog {

    private final int mColumnSelected;
    private final List<List<Object>> mTableData;
    
    private final OnFilteringListener mListener;
    public interface OnFilteringListener {
        void onFilteringComplete(List<FilteredData> filterData);
    }

    /**
     * Creates new form FilterPopup
     * @param parent
     * @param modal
     * @param columnSelected
     * @param tableData
     * @param listener
     */
    public FilterDialog(java.awt.Frame parent, boolean modal, int columnSelected, 
            List<List<Object>> tableData, OnFilteringListener listener) {
        super(parent, modal);
        initComponents();
        mTableData = tableData;
        mColumnSelected = columnSelected;
        mListener = listener;
        
        GradeUtils.centerFrame(this);
    }
    
    private void _filter(String filter) {
        GradeApp.executor().execute(() -> {
            List<FilteredData> filteredData = new ArrayList<>();

            for (int row=1; row<mTableData.size(); row++) {
                Object content = mTableData.get(row).get(mColumnSelected);

                List<Object> columns = new ArrayList<>();
                final String contentStr = (String) content;
                if (contentStr == null)
                    continue;
                
                if (filter.toLowerCase().equals(contentStr.toLowerCase())) {
                    columns.addAll(mTableData.get(row));
                    FilteredData f = new FilteredData(row, columns);
                    
                    filteredData.add(f);
                }
            }

            mListener.onFilteringComplete(filteredData);
            setVisible(false);
            dispose();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        filterTxField = new javax.swing.JTextField();
        tajosJLabel2 = new com.tajos.studio.components.TajosJLabel();
        filterBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filter");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tajosJLabel2.setForeground(new java.awt.Color(22, 28, 72));
        tajosJLabel2.setText("Enter something to filter:");
        tajosJLabel2.setDefaultFont(10);

        filterBtn.setBackground(new java.awt.Color(247, 245, 251));
        filterBtn.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        filterBtn.setText("Filter");
        filterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tajosJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterTxField, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filterBtn)
                .addGap(210, 210, 210))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(tajosJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterTxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filterBtn)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterBtnActionPerformed
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        _filter(filterTxField.getText());
    }//GEN-LAST:event_filterBtnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ImageIcon icon = new ImageIcon(WorkBookActivity.class.getResource("/res/grading-logo.png"));
        setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton filterBtn;
    private javax.swing.JTextField filterTxField;
    private javax.swing.JPanel jPanel1;
    private com.tajos.studio.components.TajosJLabel tajosJLabel2;
    // End of variables declaration//GEN-END:variables
}
