package com.tajos.studio.dialogs;

import com.tajos.studio.GradeApp;
import com.tajos.studio.components.TajosTable;
import com.tajos.studio.util.GradeUtils;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rene Tajos Jr
 */
public class FormulasCopyDialog extends javax.swing.JDialog {

    private final OnCopyListener listener;
    private final TajosTable mTable;
    
    public interface OnCopyListener {
        void onCopyingDone(Map<Integer, Map<Integer, String>> formulas);
    }

    /**
     * Creates new form NewJDialog
     * @param parent
     * @param modal
     * @param table
     * @param listener
     */
    public FormulasCopyDialog(java.awt.Frame parent, boolean modal, 
            TajosTable table,
            FormulasCopyDialog.OnCopyListener listener) 
    {
        super(parent, modal);
        mTable = table;
        this.listener = listener;
        
        initComponents();
        _init();
        
        GradeUtils.centerFrame(this);
    }
    
    private void _init() {
        GradeApp.executor().execute(() -> {
            Map<Integer, Map<Integer, String>> formulas = new HashMap<>();
            for (Map.Entry<Integer, Map<Integer, String>> entry1 : mTable.getInvoker().getFormulas().entrySet()) {
                int row = entry1.getKey();
                Map<Integer, String> columnEntry = entry1.getValue();

                formulas.put(row, new HashMap(columnEntry));
            }
            
            try {
                Thread.sleep(200);
                listener.onCopyingDone(formulas);
            } catch (InterruptedException ex) {
                GradeUtils.showErrorDialog(ex.getMessage(), "Something went wrong");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tajosJLabel1 = new com.tajos.studio.components.TajosJLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 28, 72), 2));
        jPanel1.setLayout(new com.tajos.studio.layoutmanagers.GravityLayout());

        tajosJLabel1.setForeground(new java.awt.Color(22, 28, 72));
        tajosJLabel1.setText("Please wait a moment...");
        tajosJLabel1.setDefaultFont(12);
        jPanel1.add(tajosJLabel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private com.tajos.studio.components.TajosJLabel tajosJLabel1;
    // End of variables declaration//GEN-END:variables
}
