package com.tajos.studio.dialogs;

import com.tajos.studio.util.GradeUtils;
import java.awt.Dimension;
import java.awt.geom.Rectangle2D;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JFrame;
import javax.swing.JWindow;

/**
 *
 * @author Rene Tajos Jr.
 */
public class NotificationPopup extends JWindow {

    /**
     * Creates new form NotificationPopup2
     * @param str
     */
    public NotificationPopup(String str) {
        initComponents();
        
        setBackground(GradeUtils.Colors.transparent);
        _init(str);
    }
    
    private void _init(String str) {
        Rectangle2D txRectangle2D = GradeUtils.getTextRect(
                notifyLbl.getFontMetrics(notifyLbl.getFont()), 
                notifyLbl.getGraphics(), str);
        
        notifyLbl.setText(str);
        notifyLbl.setPreferredSize(new Dimension((int)txRectangle2D.getWidth()+10, notifyLbl.getPreferredSize().height));
        notifyLbl.resizeWithPreferredSize();
    }
    
    public void show(JFrame frame) {
        int x = frame.getBounds().x + (frame.getBounds().width - getPreferredSize().width);
        int y = frame.getBounds().y + (frame.getBounds().height - getPreferredSize().height);
        
        setBounds(x, y, getPreferredSize().width, getPreferredSize().height);
        setVisible(true);
        
        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                hideNotification();
                timer.cancel();
            }
        }, 3000);
    }
    
    public void hideNotification() {
        setVisible(false);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new com.tajos.studio.graphics.RoundedPanel();
        notifBell = new com.tajos.studio.components.ImageViewer();
        notifyLbl = new com.tajos.studio.components.TajosJLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setRadius(30);
        mainPanel.setShadowEnabled(true);
        mainPanel.setShadowSize(2);
        com.tajos.studio.layoutmanagers.GravityLayout gravityLayout1 = new com.tajos.studio.layoutmanagers.GravityLayout();
        gravityLayout1.setHorizontalGap(10);
        mainPanel.setLayout(gravityLayout1);

        notifBell.setImageResource(new javax.swing.ImageIcon(getClass().getResource("/icons/notification.png"))); // NOI18N
        notifBell.setImageType(com.tajos.studio.components.ImageViewer.ImageType.COVER);
        notifBell.setPreferredSize(new java.awt.Dimension(30, 30));
        mainPanel.add(notifBell);

        notifyLbl.setForeground(new java.awt.Color(22, 28, 72));
        notifyLbl.setText("Notificationn");
        notifyLbl.setDefaultFont(12);
        notifyLbl.setPreferredSize(new java.awt.Dimension(70, 16));
        mainPanel.add(notifyLbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.tajos.studio.graphics.RoundedPanel mainPanel;
    private com.tajos.studio.components.ImageViewer notifBell;
    private com.tajos.studio.components.TajosJLabel notifyLbl;
    // End of variables declaration//GEN-END:variables
    private void setDefaultCloseOperation(int EXIT_ON_CLOSE) {}
    private void setUndecorated(boolean b) {}
}
