package com.tajos.studio.dialogs;

import com.tajos.studio.net.DBManager;
import com.tajos.studio.activities.AboutAppActivity;
import com.tajos.studio.activities.MyProfileActivity;
import com.tajos.studio.util.GradeUtils;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Point;
import javax.swing.JWindow;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Rene Tajos Jr.
 */
public class UserProfileDialog extends JWindow {

    /**
     * Creates new form UserProfilePopupMenu
     */
    public UserProfileDialog() {
        initComponents();
        
        setBackground(new Color(0,0,0,0));
        sep1.setSize(getWidth(), sep1.getHeight());
        sep2.setSize(getWidth(), sep2.getHeight());
    }

    /**
     * Override to disable shadow, so it can render shadow the next open of this JWindow.
     * @param b 
     */
    @Override
    public void setVisible(boolean b) {
        mainPanel.setHasShadow(false);
        super.setVisible(b);
    }
    
    public void show(Component invoker, int x, int y) {
        Point invokerLoc = invoker.getLocationOnScreen();
        
        setBounds(invokerLoc.x + x, invokerLoc.y + y, getPreferredSize().width, getPreferredSize().height);
        setVisible(true);
    }
    
    public void hideWindow() {
        setVisible(false);
    }
    
    private void _updateUI() {
        mainPanel.revalidate();
        mainPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new com.tajos.studio.graphics.RoundedPanel();
        jPanel6 = new javax.swing.JPanel();
        imageViewer1 = new com.tajos.studio.components.ImageViewer();
        profileLbl1 = new com.tajos.studio.components.TajosJLabel();
        sep1 = new javax.swing.JSeparator() {
            int x = mainPanel.getShadowSize();
            @Override
            public void paintComponent(Graphics g) {
                g.setColor(new Color(227,219,242));
                g.fillRect(x, sep1.getHeight()/2, sep1.getWidth(), 1);
            }
        };
        profilePanel = new javax.swing.JPanel();
        profileLbl = new com.tajos.studio.components.TajosJLabel();
        aboutPanel = new javax.swing.JPanel();
        aboutLbl = new com.tajos.studio.components.TajosJLabel();
        sep2 = new javax.swing.JSeparator() {
            int x = mainPanel.getShadowSize();
            @Override
            public void paintComponent(Graphics g) {
                g.setColor(new Color(227,219,242));
                g.fillRect(x, sep2.getHeight()/2, sep2.getWidth(), 1);
            }
        };
        switchAccntPanel = new javax.swing.JPanel();
        switchAccntLbl = new com.tajos.studio.components.TajosJLabel();
        signOutPanel = new javax.swing.JPanel();
        signOutLbl = new com.tajos.studio.components.TajosJLabel();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setRadius(20);
        mainPanel.setShadowEnabled(true);
        com.tajos.studio.layoutmanagers.ListViewLayout listViewLayout1 = new com.tajos.studio.layoutmanagers.ListViewLayout();
        listViewLayout1.setFixHeight(true);
        listViewLayout1.setFixWidth(true);
        mainPanel.setLayout(listViewLayout1);

        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(208, 36));
        com.tajos.studio.layoutmanagers.GravityLayout gravityLayout1 = new com.tajos.studio.layoutmanagers.GravityLayout();
        gravityLayout1.setGravity(com.tajos.studio.layoutmanagers.GravityLayout.Gravity.LEFT);
        gravityLayout1.setLeftPadding(20);
        gravityLayout1.setTopPadding(20);
        gravityLayout1.setAdjustableSize(true);
        gravityLayout1.setBottomPadding(5);
        gravityLayout1.setHorizontalGap(20);
        jPanel6.setLayout(gravityLayout1);

        imageViewer1.setImageResource(new javax.swing.ImageIcon(getClass().getResource("/res/grading-logo.png"))); // NOI18N
        imageViewer1.setImageType(com.tajos.studio.components.ImageViewer.ImageType.FILL);
        imageViewer1.setPreferredSize(new java.awt.Dimension(16, 16));
        jPanel6.add(imageViewer1);

        profileLbl1.setForeground(new java.awt.Color(22, 28, 72));
        profileLbl1.setText("Graede");
        profileLbl1.setDefaultFont(12);
        jPanel6.add(profileLbl1);

        mainPanel.add(jPanel6);

        sep1.setPreferredSize(new java.awt.Dimension(212, 5));
        mainPanel.add(sep1);

        profilePanel.setOpaque(false);
        profilePanel.setPreferredSize(new java.awt.Dimension(208, 30));
        profilePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profilePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profilePanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                profilePanelMousePressed(evt);
            }
        });
        com.tajos.studio.layoutmanagers.GravityLayout gravityLayout2 = new com.tajos.studio.layoutmanagers.GravityLayout();
        gravityLayout2.setGravity(com.tajos.studio.layoutmanagers.GravityLayout.Gravity.LEFT);
        gravityLayout2.setHorizontalGap(10);
        gravityLayout2.setLeftPadding(0);
        gravityLayout2.setOrientation(com.tajos.studio.layoutmanagers.GravityLayout.Orientation.HORIZONTAL);
        gravityLayout2.setPadding(20);
        gravityLayout2.setTopPadding(10);
        profilePanel.setLayout(gravityLayout2);

        profileLbl.setForeground(new java.awt.Color(22, 28, 72));
        profileLbl.setText("My Profile");
        profileLbl.setDefaultFont(12);
        profilePanel.add(profileLbl);

        mainPanel.add(profilePanel);

        aboutPanel.setOpaque(false);
        aboutPanel.setPreferredSize(new java.awt.Dimension(208, 30));
        aboutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aboutPanelMousePressed(evt);
            }
        });
        com.tajos.studio.layoutmanagers.GravityLayout gravityLayout3 = new com.tajos.studio.layoutmanagers.GravityLayout();
        gravityLayout3.setGravity(com.tajos.studio.layoutmanagers.GravityLayout.Gravity.LEFT);
        gravityLayout3.setHorizontalGap(10);
        gravityLayout3.setLeftPadding(0);
        gravityLayout3.setOrientation(com.tajos.studio.layoutmanagers.GravityLayout.Orientation.HORIZONTAL);
        gravityLayout3.setPadding(20);
        gravityLayout3.setTopPadding(10);
        aboutPanel.setLayout(gravityLayout3);

        aboutLbl.setForeground(new java.awt.Color(22, 28, 72));
        aboutLbl.setText("About This App");
        aboutLbl.setDefaultFont(12);
        aboutPanel.add(aboutLbl);

        mainPanel.add(aboutPanel);

        sep2.setPreferredSize(new java.awt.Dimension(212, 5));
        mainPanel.add(sep2);

        switchAccntPanel.setOpaque(false);
        switchAccntPanel.setPreferredSize(new java.awt.Dimension(208, 30));
        switchAccntPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                switchAccntPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                switchAccntPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                switchAccntPanelMousePressed(evt);
            }
        });
        com.tajos.studio.layoutmanagers.GravityLayout gravityLayout4 = new com.tajos.studio.layoutmanagers.GravityLayout();
        gravityLayout4.setGravity(com.tajos.studio.layoutmanagers.GravityLayout.Gravity.LEFT);
        gravityLayout4.setHorizontalGap(10);
        gravityLayout4.setLeftPadding(0);
        gravityLayout4.setOrientation(com.tajos.studio.layoutmanagers.GravityLayout.Orientation.HORIZONTAL);
        gravityLayout4.setPadding(20);
        gravityLayout4.setTopPadding(10);
        switchAccntPanel.setLayout(gravityLayout4);

        switchAccntLbl.setForeground(new java.awt.Color(22, 28, 72));
        switchAccntLbl.setText("Switch Account");
        switchAccntLbl.setDefaultFont(12);
        switchAccntPanel.add(switchAccntLbl);

        mainPanel.add(switchAccntPanel);

        signOutPanel.setOpaque(false);
        signOutPanel.setPreferredSize(new java.awt.Dimension(208, 30));
        signOutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signOutPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signOutPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signOutPanelMousePressed(evt);
            }
        });
        com.tajos.studio.layoutmanagers.GravityLayout gravityLayout5 = new com.tajos.studio.layoutmanagers.GravityLayout();
        gravityLayout5.setGravity(com.tajos.studio.layoutmanagers.GravityLayout.Gravity.LEFT);
        gravityLayout5.setHorizontalGap(10);
        gravityLayout5.setLeftPadding(0);
        gravityLayout5.setOrientation(com.tajos.studio.layoutmanagers.GravityLayout.Orientation.HORIZONTAL);
        gravityLayout5.setPadding(20);
        gravityLayout5.setTopPadding(10);
        signOutPanel.setLayout(gravityLayout5);

        signOutLbl.setForeground(new java.awt.Color(22, 28, 72));
        signOutLbl.setText("Sign Out");
        signOutLbl.setDefaultFont(12);
        signOutPanel.add(signOutLbl);

        mainPanel.add(signOutPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signOutPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutPanelMousePressed
        setVisible(false);
        DBManager.getInstance().signOutUser();      
    }//GEN-LAST:event_signOutPanelMousePressed

    private void profilePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePanelMouseEntered
        profileLbl.setBorder(javax.swing.BorderFactory.createLineBorder(GradeUtils.Colors.darkBlueColor));
        _updateUI();
    }//GEN-LAST:event_profilePanelMouseEntered

    private void profilePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePanelMouseExited
        profileLbl.setBorder(new EmptyBorder(0, 0, 0, 0));
        _updateUI();
    }//GEN-LAST:event_profilePanelMouseExited

    private void aboutPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutPanelMouseEntered
        aboutLbl.setBorder(javax.swing.BorderFactory.createLineBorder(GradeUtils.Colors.darkBlueColor));
        _updateUI();
    }//GEN-LAST:event_aboutPanelMouseEntered

    private void aboutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutPanelMouseExited
        aboutLbl.setBorder(new EmptyBorder(0, 0, 0, 0));
        _updateUI();
    }//GEN-LAST:event_aboutPanelMouseExited

    private void switchAccntPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switchAccntPanelMouseEntered
        switchAccntLbl.setBorder(javax.swing.BorderFactory.createLineBorder(GradeUtils.Colors.darkBlueColor));
        _updateUI();
    }//GEN-LAST:event_switchAccntPanelMouseEntered

    private void switchAccntPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switchAccntPanelMouseExited
        switchAccntLbl.setBorder(new EmptyBorder(0, 0, 0, 0));
        _updateUI();
    }//GEN-LAST:event_switchAccntPanelMouseExited

    private void signOutPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutPanelMouseEntered
        signOutLbl.setBorder(javax.swing.BorderFactory.createLineBorder(GradeUtils.Colors.darkBlueColor));
        _updateUI();
    }//GEN-LAST:event_signOutPanelMouseEntered

    private void signOutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutPanelMouseExited
        signOutLbl.setBorder(new EmptyBorder(0, 0, 0, 0));
        _updateUI();
    }//GEN-LAST:event_signOutPanelMouseExited

    private void profilePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePanelMousePressed
        new MyProfileActivity().setVisible(true);
        hideWindow();
    }//GEN-LAST:event_profilePanelMousePressed

    private void aboutPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutPanelMousePressed
       new AboutAppActivity().setVisible(true);
       hideWindow();
    }//GEN-LAST:event_aboutPanelMousePressed

    private void switchAccntPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switchAccntPanelMousePressed
        DBManager.getInstance().signOutUser();
        hideWindow();
    }//GEN-LAST:event_switchAccntPanelMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.tajos.studio.components.TajosJLabel aboutLbl;
    private javax.swing.JPanel aboutPanel;
    private com.tajos.studio.components.ImageViewer imageViewer1;
    private javax.swing.JPanel jPanel6;
    private com.tajos.studio.graphics.RoundedPanel mainPanel;
    private com.tajos.studio.components.TajosJLabel profileLbl;
    private com.tajos.studio.components.TajosJLabel profileLbl1;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep2;
    private com.tajos.studio.components.TajosJLabel signOutLbl;
    private javax.swing.JPanel signOutPanel;
    private com.tajos.studio.components.TajosJLabel switchAccntLbl;
    private javax.swing.JPanel switchAccntPanel;
    // End of variables declaration//GEN-END:variables

}
